version: "3.5"

#
#  Required lines to change (all examples enclosed in <> ):
#  29)replace with email for letsencrypt 
#  40)replace with host&domain of service. note that domains should be quoted in backticks. 
#  45)add user name and password hash. hash must be produced via htpasswd, escape dollar signs by doubling, ie $ > $$. example escaped hash for 'password'- $$apr1$$6Kw4hM.I$$v65KE1axCdMMHq0gT4f9K0
#  58&59) replace with desired root password and standard password for database.
#  74)replace with host&domain of service. note that domains should be quoted in backticks.
#  78)standard db password; must be same as password used in line 59.


services:

  traefik:
    image: traefik:latest
    container_name: traefik
    command:
    #  - --log.level=DEBUG
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.email=<example@email.tld>
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
    ports:
    #  - 8080:8080
      - 443:443
      - 80:80
    labels:
      - traefik.enable=true
      # Dashboard
      - traefik.http.routers.traefik.rule=(Host(`<host.example.tld>`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`)))
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls.certresolver=le
      - traefik.http.routers.traefik.middlewares=admin
      - traefik.http.middlewares.admin.basicauth.users=<username>:<escappedpasswordhash>
   
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
  db:
    container_name: nextcloud-db
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --log-basename=mariadblog
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=<rootmysqlpass>
      - MYSQL_PASSWORD=<mysqlpass>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nextcloud:
    container_name: nextcloud
    image: nextcloud
    restart: always
    links:
      - db
    volumes:
      - ./nextcloud:/var/www/html

    labels:
      - traefik.enable=true
      - traefik.http.routers.nextcloud.rule=Host(`<host.example.tld>`)
      - traefik.http.routers.nextcloud.entrypoints=websecure
      - traefik.http.routers.nextcloud.tls.certresolver=le
    environment:
      - MYSQL_PASSWORD=<mysqlpass>
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
volumes:
  db: