#  Required lines to change (all examples enclosed in <> ):
#  19)email for letsencrypt 
#  29&37)host and domain of service, quote in backticks
#  34)credentials for traefik dashboard. hash must be produced via htpasswd, escape dollar signs by doubling, ie $ > $$. example escaped hash for 'password'- $$apr1$$6Kw4hM.I$$v65KE1axCdMMHq0gT4f9K0
#
version: "3.5"
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    command:
#      - --log.level=DEBUG
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.tlschallenge=true
      - --certificatesresolvers.le.acme.email=<email@example.tld>
      - --certificatesresolvers.le.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.le.acme.httpchallenge=true
      - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
    ports:
      - 443:443
      - 80:80
    labels:
      - traefik.enable=true
      # Dashboard
      - traefik.http.routers.twebsec.rule=Host(`<traefickhostname.domain.tld>`) 
      - traefik.http.routers.twebsec.service=api@internal
      - traefik.http.routers.twebsec.entrypoints=websecure
      - traefik.http.routers.twebsec.tls.certresolver=le
      - traefik.http.routers.twebsec.middlewares=dashauth
      - traefik.http.middlewares.dashauth.basicauth.users=<username>:<escapedpasswordhash>
      # https redirect
      - traefik.http.routers.tweb.entrypoints=web
      - traefik.http.routers.tweb.rule=Host(`<traefickhostname.domain.tld>`)
      - traefik.http.routers.tweb.middlewares=t-https
      - traefik.http.middlewares.t-https.redirectscheme.scheme=https
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - traefik-bridge
networks:
  traefik-bridge:
    name: proxynet